---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  roles:
    - deploy

  post_tasks:
    - name: "run the backend"
      become: true
      raw: ( cd ~/web && npm install && npm run build && pm2 stop default && pm2 start npm -- start )
